### ISSUE TITLE
colors

### ISSUE THREAD

**Issue by kumarneetesh24** [RECursion-NITD/Website#3]
Use more than two colours. Can't we use other combination than of black and white, looks old school

**Comment by kumarneetesh24** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Static Pages](https://trello.com/c/W6JSyYKp/1-static-pages)

**Comment by alchemist95** [comment]
i used charcoal gray with white, but surely that can be done

**Comment by kumarneetesh24** [comment]
okay, try some other combination.

**Comment by kumarneetesh24** [comment]
Navbar menu hover and selected color should be changed
