### ISSUE TITLE
Past Events UI

### ISSUE THREAD

**Issue by gcnit** [RECursion-NITD/Website#53]
Different sizes for both the contest boxes

![Different sizes for both the contest boxes](https://cloud.githubusercontent.com/assets/4833751/20664420/2973b52a-b581-11e6-95bd-f1cdf5926960.png)

@kumarneetesh24

**Comment by alchemist95** [comment]
bhaiya... take a look at this
![screenshot from 2016-11-28 16 01 47](https://cloud.githubusercontent.com/assets/12803205/20665069/17dce342-b584-11e6-9002-8c05b3f5a48c.png)
Can i consider the issue closed ? :)

**Comment by gcnit** [comment]
The issue persists for me even after hard reload

**Comment by alchemist95** [comment]
It will as long as my branch isnt merged, bhaiya. I dont have admin rights. If u wish, you can merge my branch and check it out.

**Comment by alchemist95** [comment]
i meant the last commit in my branch :+1:
