### ISSUE TITLE
How to get started with Competitive Coding

### ISSUE THREAD

**Issue by Aman8050** [RECursion-NITD/Website#63]
Write small content with topic on main page of website... click more...opens new page with complete content.

**Comment by etotientz** [comment]
Do we have the content of How to get started with competitive programming? If yes then I can fix this issue.

**Comment by Aman8050** [comment]
No, not yet....Either refer Chandak's quora blog or ask from coder...

**Comment by Aman8050** [comment]
@etotientz  Ya u can fix the issue...
